django_base_skeleton/api/urls.py
from django.conf.urls.defaults import patterns, include, url
from piston.resource import Resource
from api.handlers import CalcHandler, PollHandler, ChoiceHandler

class CsrfExemptResource( Resource ):
  def __init__( self, handler, authentication = None ):
    super( CsrfExemptResource, self ).__init__( handler, authentication )
    self.csrf_exempt = getattr( self.handler, 'csrf_exempt', True )

calc_resource = CsrfExemptResource( CalcHandler )
poll_resource = CsrfExemptResource( PollHandler )
choice_resource = CsrfExemptResource( ChoiceHandler )

urlpatterns = patterns( '',
  url( r'^calc/(?P<expression>.*)$', calc_resource ), #even though it says ^calc it takes the path api/calc as this file is included using the ^api/ path
  url( r'^poll/(?P<id>.*)$', poll_resource),
  url( r'^poll/$', poll_resource),
  url( r'^choice/(?P<id>\d*)$', choice_resource),
  url( r'^choice/(?P<id>\d*)/(?P<action>increment)$', choice_resource),
  url( r'^choice/$', choice_resource),
)

django_base_skeleton/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
  # Examples:
  # url(r'^$', 'django_base_skeleton.views.home', name='home'),
  # url(r'^django_base_skeleton/', include('django_base_skeleton.foo.urls')),

  # Uncomment the admin/doc line below to enable admin documentation:
  # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

  # Uncomment the next line to enable the admin:
  url(r'^admin/', include(admin.site.urls)),

  url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
  url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),

  url(r'^reset_password/$', 'django.contrib.auth.views.password_reset', name='reset_password'),
  url(r'^reset_password_done/$', 'django.contrib.auth.views.password_reset_done', name='reset_password_done'),
  url(r'^reset_password_complete/$', 'django.contrib.auth.views.password_reset_complete', name='reset_password_complete'),
  url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='reset_password_confirm'),
  # at this point if you have not setup your mail settings, you will get [Errno 111] Connection refused

  url(r'^api/', include('django_base_skeleton.api.urls')), #>_<
  
  url(r'^$', 'django_base_skeleton.polls.views.home', name='home'), #>_<
  
  url(r'^foo/$', 'django_base_skeleton.polls.views.foo', name='foo'), #>_<

  url(r'^polls/$', 'django_base_skeleton.polls.views.showPolls', name='showPolls'), #>_<
  url(r'^poll/create/$', 'django_base_skeleton.polls.views.createPoll', name='createPoll'), #>_<
  url(r'^choice/create/$', 'django_base_skeleton.polls.views.createChoice', name='createChoice'), #>_<

)

django_base_skeleton/api/models.py
from django.db import models

# Create your models here.

django_base_skeleton/polls/models.py
from django.db import models

# Create your models here.
class Poll(models.Model):
  question = models.CharField(max_length=200)
  pub_date = models.DateField('date published')
  polling_ended = models.BooleanField() #added to demonstrate South. So, if you want to try south, create the initial db with this commented
  #created = models.DateTimeField(auto_now_add=True) #added to demonstrate South. So, if you want to try south, create the initial db with this commented
  def __unicode__(self):
    return self.question
    
class Choice(models.Model):
  poll = models.ForeignKey(Poll)
  choice = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)

  def __unicode__(self):
    return self.poll.question + " - " + self.choice

django_base_skeleton/api/views.py
# Create your views here.

django_base_skeleton/polls/views.py
# Create your views here.
import os

from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, redirect
from django.http import HttpResponse
from django.core.cache import cache

from polls.models import Poll, Choice

from polls.tasks import MyTask
def foo(request):
  """View to test celery tasks"""
  MyTask.delay(some_arg='foo')
  return HttpResponse('Foo!')
  
#@login_required
#def home(request):
#  return render_to_response('index.html', {})

# Example of using cache
@login_required
def home(request):
  cache_key = 'cache_key'
  cache_time = 180 # time to live in seconds
  result = cache.get(cache_key)
  if not result:
    result = 'Cache empty!'
    cache_string = 'Cache string'
    print 'Key not found'
    cache.set(cache_key, cache_string, cache_time)
  print 'Result: %s' %result
  return render_to_response('index.html', {})

@login_required
def createPoll(request):
  return render_to_response('createPoll.html', {})

@login_required
def showPolls(request):
  polls = Poll.objects.all()
  choices = Choice.objects.all()
  return render_to_response('showPolls.html', {'polls': polls, 'choices': choices})

@login_required
def createChoice(request):
  polls = Poll.objects.all()
  return render_to_response('createChoice.html', {'polls': polls})

django_base_skeleton/jinja2/testsuite/res/templates/broken.html
Before
{{ fail() }}
After

django_base_skeleton/jinja2/testsuite/res/templates/foo/test.html
FOO

django_base_skeleton/jinja2/testsuite/res/templates/syntaxerror.html
Foo
{% for item in broken %}
  ...
{% endif %}

django_base_skeleton/jinja2/testsuite/res/templates/test.html
BAR

django_base_skeleton/templates/base.html
<html>
  <head>
    <title>{% block title %}{% endblock %} | Skeleton App</title>
    <style type="text/css">
      .wrapper {
        margin: auto;
        height: 600px;
        width: 700px;
        border: 1px solid #999;
      }
    </style>
    <script type="text/javascript" src="/static/js/ext/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="/static/js/utils/utils.js"></script>
    <script type="text/javascript" src="/static/js/models/baseClass.js"></script>
  {%- block head -%}{%- endblock -%}
  </head>
  <body>
    <div class="wrapper">
      <a href="/logout/" style="float:right">Logout</a>
      {%- block wrapper -%}{%- endblock -%}
    </div>
    <form id="data">{% block formdata %}{% endblock %}</form>
  </body>
</html>

django_base_skeleton/templates/createChoice.html
{% extends 'base.html' %}

{% block title %}Create polls{% endblock %}

{% block head %}{% endblock %}

{% block wrapper %}
  <div>Create a Choice -</div>
  <br />
  <form method="post" action="/api/poll/">
    Poll - 
    <select id="pollId" name="pollId">
      <option value="-1">Select a Poll</option>
      {% for poll in polls %}
        <option value="{{poll.id}}">{{poll.question}}</option>
      {% endfor %}
    </select> <a href="/poll/create/">Add</a>
    <div style="clear:both"></div>
    Choice - <input name="choice" type="text" />
    <div style="clear:both"></div>
    <input type="submit" value=" Create " />
  </form>
  <script type="text/javascript">
  $(function() {
    $("input[type=submit]").click(function() {
      data = new Object();
      data['pollId'] = $("select[name=pollId]").val().trim();
      data['choice'] = $("input[name=choice]").val().trim();
      if (data['pollId'] != "-1" && data['choice'])
        $.ajax({
          type: "POST",
          url: "/api/choice/",
          data: data,
          success: function() {
            alert("success");
          },
          error: function() {
            alert("error");
          }
        });

      return false;
    });
  });
  </script>
{% endblock %}

django_base_skeleton/templates/createPoll.html
{% extends 'base.html' %}

{% block title %}Create polls{% endblock %}

{% block head %}{% endblock %}

{% block wrapper %}
  <div>Create a Poll -</div>
  <br />
  <form method="post" action="/api/poll/">
    Question - <input name="question" type="text" />
    <div style="clear:both"></div>
    Publication Date - <input name="pubDate" type="text" />
    <div style="clear:both"></div>
    <input type="submit" value=" Create " />
  </form>
  <script type="text/javascript">
  $(function() {
    $("input[type=submit]").click(function() {
      data = new Object();
      data['question'] = $("input[name=question]").val().trim();
      data['pubDate'] = $("input[name=pubDate]").val().trim();
      if (data['question'] && data['pubDate'])
        $.ajax({
          type: "POST",
          url: "/api/poll/",
          data: data,
          success: function() {
            alert("success");
          },
          error: function() {
            alert("error");
          }
        });

      return false;
    });
  });
  </script>
{% endblock %}

django_base_skeleton/templates/index.html
<html>
  <head>
    <title>Django Skeleton</title>
  </head>
  <body id="a">
    <a href="/logout/" style="float:right">Logout</a>
    <h1>It works!</h1>
    <p>This is the default web page for this site.</p>
    <p>The web site is running on a local server. No content has been added, yet.</p>
    <script type="text/javascript" src="/static/js/utils/utils.js"></script>
    <script type="text/javascript" src="/static/js/models/baseClass.js"></script>
    <script type="text/javascript" src="/static/js/controllers/abc.js"></script>
  </body>
</html>

django_base_skeleton/templates/showPolls.html
{% extends 'base.html' %}

{% block title %}Show Polls{% endblock %}

{% block head %}{% endblock %}

{% block wrapper %}
  <div>Polls -</div>
  <br />
  <ul>
  {% for poll in polls %}
    <li>{{poll.question}}
        <ul>
        {% for choice in poll.choice_set.all() %}
          <li>{{choice.choice}} <span class="vote_count">[{{ choice.votes }}]</span><a class="upvote" href="/api/choice/{{choice.id}}/increment">+1</a></li>
        {% endfor %}
        </ul>
    </li>
  {% endfor %}
  </ul>
  <script type="text/javascript">
  $(function() {

    $(".upvote").click(function() {
      var copy = $(this);
      $.ajax({
        url: copy.attr("href"),
        type: "GET",
        dataType: 'json',
        success: function(response, textStatus, xmlHttpRequest) {
          switch(xmlHttpRequest.getResponseHeader("Content-Type").toLowerCase().split(';')[0]){
            case "text/xml":
              // write function to build object from provided xml string
              break;
            case "application/json":
              // write function to build object from provided json string
              copy.prev('.vote_count').text('['+response.votes+']');
              break;
            default:
              console.log("Unrecognized format: Request Failed!");
          }
        },
        error: function(xmlHttpRequest,textStatus,errorThrown) {
          alert("Request Failed!");
        }
      });
      return false;
    });

  });
  </script>
{% endblock %}
{% block formdata %}
  <input type="hidden" id="choices" value="{{choices}}" />
  <input type="hidden" id="polls" value="{{polls}}" />
{% endblock %}